/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientView;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author adityamulik
 */
public class DonateBloodPanel extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    
    JPanel container;
    private EcoSystem system;
    private UserAccount user;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public DonateBloodPanel(JPanel container, EcoSystem system, UserAccount user) {
        initComponents();
        this.container = container;
        this.system = system;
        this.user = user;
        
        txtName.setText(this.user.getEmployee().getName());
        
        populateCities();
    }
    
    public void populateCities() {
        for(Network n: system.getNetworkList()) {
            networkCmbBox.addItem(n);
        }
    }
    
    public void populateHospitals(Network network) {
        cmbBoxEnterpriseList.removeAllItems();
        for (Enterprise e: network.getEnterpriseDirectory().getEnterpriseList()) {
           // System.out.println(e.getEnterpriseType().toString());
            if (e.getEnterpriseType() == Enterprise.EnterpriseType.MedicalServices) {
                cmbBoxEnterpriseList.addItem(e);
            }            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDonateBloodHeading = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblHospital = new javax.swing.JLabel();
        lblBloodGroup = new javax.swing.JLabel();
        btnDonateBlood = new com.k33ptoo.components.KButton();
        networkCmbBox = new javax.swing.JComboBox();
        cmbBoxEnterpriseList = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        txtName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBoxBloodGroup = new javax.swing.JComboBox<>();
        lblQuestion = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblBloodGroup1 = new javax.swing.JLabel();
        txtDiseases = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(940, 663));

        lblDonateBloodHeading.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblDonateBloodHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonateBloodHeading.setText("Blood Donation Form");

        lblName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblName.setText("Full Name:");

        lblCity.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCity.setText("City:");

        lblHospital.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblHospital.setText("Hospital:");

        lblBloodGroup.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblBloodGroup.setText("Blood Group:");

        btnDonateBlood.setText("Donate Blood Now");
        btnDonateBlood.setkBackGroundColor(new java.awt.Color(204, 0, 51));
        btnDonateBlood.setkEndColor(new java.awt.Color(204, 0, 51));
        btnDonateBlood.setkHoverEndColor(new java.awt.Color(204, 0, 51));
        btnDonateBlood.setkHoverForeGround(new java.awt.Color(204, 0, 51));
        btnDonateBlood.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnDonateBlood.setkSelectedColor(new java.awt.Color(204, 0, 51));
        btnDonateBlood.setkStartColor(new java.awt.Color(204, 0, 51));
        btnDonateBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonateBloodActionPerformed(evt);
            }
        });

        networkCmbBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        networkCmbBox.setForeground(new java.awt.Color(25, 56, 82));
        networkCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkCmbBoxActionPerformed(evt);
            }
        });

        cmbBoxEnterpriseList.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        cmbBoxEnterpriseList.setForeground(new java.awt.Color(25, 56, 82));

        txtName.setBorder(null);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jComboBoxBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A posiitve (A+)", "A negative (A-)", "B positive (B+)", "B negative (B-)", "AB positive (AB+)", "AB negative (AB-)", "O positive (O+)", "O negative (O-)" }));

        lblQuestion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblQuestion.setText("When did ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Donated ever", "Within past one week", "Within past one month", "Within past two months" }));

        lblBloodGroup1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblBloodGroup1.setText("Any diseases?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiseases)
                            .addComponent(lblBloodGroup1)
                            .addComponent(jSeparator2)
                            .addComponent(lblBloodGroup)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, 0, 357, Short.MAX_VALUE)
                            .addComponent(jComboBoxBloodGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbBoxEnterpriseList, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHospital, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                                .addComponent(networkCmbBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(555, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(btnDonateBlood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDonateBloodHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblDonateBloodHeading)
                .addGap(59, 59, 59)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(networkCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHospital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbBoxEnterpriseList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBloodGroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBloodGroup1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiseases, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnDonateBlood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void networkCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkCmbBoxActionPerformed
        // TODO add your handling code here:
        try {
            populateHospitals((Network) networkCmbBox.getSelectedItem());
        } catch (Exception c) {
           // System.out.println("Error");
        }
    }//GEN-LAST:event_networkCmbBoxActionPerformed

    private void btnDonateBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonateBloodActionPerformed
        // TODO add your handling code here:
        if(txtName.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please enter your name!");
            return;
        }
        
        if(networkCmbBox.getSelectedItem().toString().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please select a city!");
            return;
        }
        
        if(cmbBoxEnterpriseList.getSelectedItem().toString().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please select a hospital!");
            return;
        }
        
        if(jComboBoxBloodGroup.getSelectedItem().toString().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please select a blood group");
        }
        
        
        system.getAppointmentDirectory().createAppointment(user, null, "Pending", jComboBoxBloodGroup.getSelectedItem().toString(), new Date(), true, null);
        JOptionPane.showMessageDialog(this, "Blood Donation appointment successfully created!");
        txtName.setText("");
    }//GEN-LAST:event_btnDonateBloodActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnDonateBlood;
    private javax.swing.JComboBox cmbBoxEnterpriseList;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxBloodGroup;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblBloodGroup1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDonateBloodHeading;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JComboBox networkCmbBox;
    private javax.swing.JTextField txtDiseases;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
